ARG version
FROM almalinux:${version:-9}
ENV   COURSE="Devops" \
      TRAINER="Sivalumar"
 ARG     DURATION="120hrs"
 RUN echo "Hi ${COURSE}, ${DURATION} , ${TRAINER} , ${version}"
CMD ["sleep" ,"1000"]